feat-fe: 지원자 프로세스 이동 구현
woowacourse-teams/2024-cruru pull request #100
Opened 2024-07-22 13:58 UTC by lurgi

## 작업 내용
- 지원자 프로세스 이동 구현

## 참고 사항
- MSW 모킹을 완전히 구현하지 않고, Console로 확인할 수 있도록 만들었습니다.

## 관련 이슈
-

2024-07-22 16:04 UTC, llqqssttyy requested changes
앗, 러기 혹시 저녁에 말씀드린 대로 이슈를 새로 생성하고 새롭게 생긴 브랜치에서 PR을 보낸 것 맞나요? 
target 브랜치는 올바르게 되어 있는데, 브랜치의 issue ID가 제 것보다 앞서 있어서 말씀 드려요.

* 기존에 있던 develop(현 develop-legacy)의 커밋 기록이 얽혀 있어 부분 squash, cherry pick 모두 되지 않는 문제 발생(커밋 정리 불가 상태)
* 기존 develop 브랜치(현 develop-legacy)의 커밋 기록을 모두 버리고 `스프린트 1.0`으로 squash할 수 밖에 없었음.
* 기존 develop(현 develop-legacy)에서 생성된 분기는 위 문제를 다시 야기할 가능성이 높아 폐기 결정.

=> **결론은 '지금부터 작업하는 내용은 새로운 develop 브랜치에서 뽑힌 분기여야 한다'입니다!**

만약 기존의 이슈가 open 상태라 그대로 둔 것이라면, 기존 issue와 PR 모두 close 하고 새로운 이슈를 생성해 새로운 브랜치에서 다시 커밋을 올려주세요!(cherry pick을 사용해도 되는지 여부는 도비에게 다시 여쭤볼게요)

알림이 가도록 RC 보냅니다!

2024-07-23 01:44 UTC, seongjinme reviewed
고생 많으셨어요. 코드에 대해서는 특별히 피드백 드릴 점이 없고, `endPoint.ts`에 임시로 들어간 경로 상수에 주석 하나 추가해주시는 것만 제안드려 봅니다. 감사합니다!

2024-07-23 03:02 UTC, seongjinme approved these changes

2024-07-23 04:20 UTC, llqqssttyy approved these changes
작업 고생하셨습니다~ 고칠 부분 딱히 보이지 않아서 approve 드려요.

2024-07-23 04:20 UTC, llqqssttyy commented on frontend/src/hooks/useProcess/index.ts
> +    queryKey: ['dashboard', DASHBOARD_ID],
나중에 queryKey가 많아지면 'dashboard'도 상수로 관리하는 방법을 생각해볼 수 있을 것 같네요. 합칠 때 다시 이야기 해봅시다.

2024-07-23 04:20 UTC, merged