chore: 초기세팅
woowacourse-teams/2024-cruru pull request #16
Opened 2024-07-12 00:09 UTC by lurgi

1. webpack + typescript + react 초기 세팅
2. PandaCSS 세팅
3. Storybook 세팅
4. RTL 세팅
5. Lint + Prettier 세팅

## 작업 내용
- 초기세팅

## 참고 사항
fork를 미리 떠서 upstream push를 하려고 했는데 막혀있는 것 같아서 PR로 남깁니다. 체크 한번 하고 머지 이후해용

## 관련 이슈

## PR 체크리스트
초기세팅이므로 체크안합니다.
- [] 테스트는 모두 통과했나요?
- [] 빌드는 성공했나요?
- [] 코드 포맷팅을 진행했나요?
- [] PR 내부의 예시는 삭제하셨나요?

2024-07-12 01:23 UTC, llqqssttyy requested changes

2024-07-12 01:23 UTC, llqqssttyy commented on panda.config.ts
> +  // outdir: "styled-system",
사용하지 않는 주석 발견🚨🚨🚨 지워주세요!

2024-07-12 01:32 UTC, seongjinme requested changes
러기 정말 고생 많으셨어요. 🙏
사소하지만 몇가지 개선되었으면 하는 부분들이 있어 코멘트와 함께 RC 드립니다. 
관련하여 궁금하신 내용이 있으시면 언제든 말씀 주세요!

2024-07-12 01:32 UTC, seongjinme commented on webpack.config.js
> +  module: {
현재 웹팩 설정에는 이미지 파일 처리 부분이 없어서, 이대로라면 `prod`용 빌드 파일에 이미지들이 누락될 것 같아요.
Webpack 5버전에 맞춰서 아래 설정을 추가해주시면 좋을 것 같습니다. 보다 상세한 설명은 [이 링크](https://pozafly.github.io/environment/webpack-boilerplate/#%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%B2%98%EB%A6%AC)를 참고해주세요. 🙏 

```JavaScript
module.exports = {
  module: {
    rules: [

      // 이미지 파일 처리 추가
      {
        test: /\.(png|svg|jpe?g|gif|webp)$/i,
        type: 'asset', 
        parser: {
          dataUrlCondition: {
            maxSize: 4 * 1024, // 4kb 이하라면 url-loader로, 이상이면 file-loader로 동작
          },
        },
        generator: {
          filename: 'assets/images/[name]_[contenthash:8][ext]', // 임의의 해시값을 파일명에 추가하여 캐쉬 문제 방지
        },
      },

      // 나머지 설정들...
    ]
  }
}
```

참고로 위에서는 `assets/images/` 경로에 임의의 해시값이 포함된 파일명으로 빌드되도록 설정되어 있습니다. 이 또한 권장사항 중 하나인데요. 매번 빌드되는 파일명이 동일할 경우, `prod` 환경에서 브라우저나 CDN 캐쉬에 남아있는 동명의 파일이 대신 로딩될 가능성이 있습니다. 이를 방지하기 위한 방법 중 하나입니다. :)

2024-07-12 01:32 UTC, seongjinme commented on webpack.config.js
> +    filename: "bundle.js",
요 번들링 된 파일명도 해시값을 담아서 생성해주면 좋을 것 같습니다!

```suggestion
    filename: "[name]_[chunkhash:8].js",
```

2024-07-12 01:32 UTC, seongjinme commented on webpack.config.js
> +    clean: true,
이 옵션은 `dist` 폴더에 있는 찌꺼기 파일들을 제거해주는 옵션입니다. 이게 동작하려면 개발환경에 `clean-webpack-plugin` 패키지가 추가로 필요해요. 의존성을 추가해주시면 좋을 것 같습니다 🙏

2024-07-14 00:38 UTC, lurgi commented on webpack.config.js
> +  module: {
한 수 배웠어요.. 💙

2024-07-14 01:13 UTC, lurgi commented on webpack.config.js
> +  module: {
type을 asset으로 설정하면 따로 file-loader와 url-loader가 필요 없군요..! 감사합니다!

2024-07-14 01:23 UTC, lurgi commented on webpack.config.js
> +    clean: true,
감사합니다 아르! 💙
이 clean옵션으로 디렉토리 정리가 가능한 것으로 알고있습니다! 
찾아보니 webpack5버전에서 추가된 기능이라 이전까진 Plugin을 사용한 것으로 보입니다.
현 시점에서 플러그인의 경우 추가적인 기능(특정 파일을 선택해서 clean하는 것과 같은 동작)을 사용할 경우에 추가적으로 설치하면 좋을 거라 생각합니다! 혹시 제가 놓친 부분이 있을까용?!

2024-07-14 01:59 UTC, seongjinme commented on webpack.config.js
> +    clean: true,
웹팩 공식 메뉴얼을 확인해보니 `5.20.0` 버전부터 `clean` 옵션을 기본으로 제공하고 있네요 😅  
러기가 말씀해주신 내용이 맞습니다. 이 부분은 그대로 두셔도 될 것 같아요. 혼동을 드려 죄송합니다 🙏

2024-07-15 08:37 UTC, llqqssttyy approved these changes
어푸르브 드릴게요~

2024-07-15 08:38 UTC, seongjinme approved these changes

2024-07-15 08:38 UTC, merged