docs-be: RESTDocs 문서화 적용
woowacourse-teams/2024-cruru pull request #182
Opened 2024-07-25 10:38 UTC by HyungHoKim00

## 작업 내용
- API 문서 생성했습니다.

## 참고 사항
- 스프링 실행 후 localhost:8080/docs/index.html 로 들어가시면 문서를 확인할 수 있습니다.
- Request에 한글을 넣으면 build가 되지 않는 이슈가 있어, 모두 영어로 작성되어있습니다. 원인을 아신다면 말씀해주세요.

## 관련 이슈
- closes #177 

## PR 체크리스트
- [x] 테스트는 모두 통과했나요?
- [x] 빌드는 성공했나요?
- [x] 코드 포맷팅을 진행했나요?
- [x] PR 내부의 예시는 삭제하셨나요?

2024-07-25 12:53 UTC, Chocochip101 requested changes
RestDocs 의존성 추가하시느라 수고하셨습니다 :)

관련 코멘트 남겼으니 확인해주세요 🙌🏻

2024-07-25 12:53 UTC, Chocochip101 commented on backend/build.gradle
> +    // RESTDocs
```suggestion
    // Docs
```

라이브러리의 종류만 나눠놓으면 된다고 생각해, Docs 정도로도 의미 전달이 가능할 것 같습니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/build.gradle
> -    id 'jacoco'
jacoco 관련 설정을 삭제하신 이유가 있나요?

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +        Long invalidProcessId = -1L;
Wrapper Class로 설정한 이유가 있나요?

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +                .filter(document("applicant/move-process-fail/process-not-found/",
document 식별자(path)를 작성하는 컨벤션이 있나요?

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/dashboard/controller/DashboardControllerTest.java
> +        Long invalidClubId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +        Long invalidApplicantId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +        Long invalidApplicantId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +        Long invalidApplicantId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java
> +        Long invalidApplicantId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java
> +        Long invalidProcessId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
개행이 있네요.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +        Long invalidDashboardId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +        Long invalidId = -1L;
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +    @DisplayName("처음 혹은 마지막 프로세스 삭제 시도 시, 400을 응답한다.")
```suggestion
    @DisplayName("처음 또는 마지막 프로세스 삭제 시도 시, 400을 응답한다.")
```

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
위와 같은 리뷰입니다.

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/util/ControllerTest.java
>      @LocalServerPort
```suggestion
    protected RequestSpecification spec;
    
    @LocalServerPort
```

2024-07-25 12:53 UTC, Chocochip101 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
>      @DisplayName("존재하는 프로세스의 이름과 설명 변경 성공시, 200을 응답한다.")
```suggestion
    @DisplayName("존재하는 프로세스의 이름과 설명 변경 성공 시, 200을 응답한다.")
```

2024-07-26 01:08 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +        Long invalidProcessId = -1L;
아뇨...

2024-07-26 01:12 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +                .filter(document("applicant/move-process-fail/process-not-found/",
도메인명/메서드명(실패의 경우 fail 추가)/실패 사유 
입니다!

2024-07-26 01:13 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +
불필요한 코드 삭제하는 과정에서 생겼는데, 지운다고 지웠는데 남아있네요..

2024-07-26 01:23 UTC, HyungHoKim00 commented on backend/build.gradle
> -    id 'jacoco'
대답해드렸습니다^^

2024-07-26 02:07 UTC, xogns1514 requested changes
문서화 코드 추가하느라 고생하셨습니다. 양이 많아서 고생하셨겠네요. 궁금한점 남겨두었습니다.

2024-07-26 02:07 UTC, xogns1514 commented on backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java
> +    private static FieldDescriptor[] scoreAndContentDescriptor() {
ProcessController에서는 상수로 선언하셨던데, 여기는 함수로 선언하신 이유가 있나요?

2024-07-26 02:21 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java
> +    private static FieldDescriptor[] scoreAndContentDescriptor() {
함수로 통일시키고 싶었는데, 함수가 포맷팅 할때마다 순서가 이상하게 올라가는 것이 마음에 들지 않아 상수로 분리했었습니다, 어떤 전략으로 중복 로직을 처리하는게 좋을까요?

2024-07-26 04:07 UTC, closed without merging