feat-fe: 대시보드 내 공고 카드 컴포넌트 구현
woowacourse-teams/2024-cruru pull request #283
Opened 2024-08-06 09:32 UTC by seongjinme

## 작업 내용
- 동아리 대시보드 내에 노출될 공고별 카드 컴포넌트를 구현했습니다.
- 카드 컴포넌트(`RecruitmentCard`)와 부속 컴포넌트(`RecruitmentCardStat`)으로 구분되어 있습니다.

## 참고 사항
- `onClick` 관련 함수 2개를 prop으로 받도록 설계했습니다. 모두 prop으로 사전에 받아놓은 `dashboardId`를 인자로 하여 실행됩니다.
  - `onClickTitle` : 해당 공고에 대한 대시보드로 넘어가도록 하는 데에 필요합니다. 현재는 제목 영역에 적용되어 있습니다.
  - `onClickShareButton` : 해당 공고에 대한 공유용 URL을 클립보드에 복사하는 용도로 필요합니다.

### 리뷰시 꼭 살펴주셨으면 하는 사항
- 카드 영역 hover시 약간의 애니메이션 효과를 추가했습니다. 스타일 측면에서 적절한지 체크해주세요.
- 버튼 액션이 2곳에 존재하기에, 현재는 1) 제목 영역과 2) 공유버튼 영역에 각각 적용한 뒤 해당 영역들에만 cursor 처리를 했습니다.

## 관련 이슈
- closes #268 

## PR 체크리스트
- [x] 테스트는 모두 통과했나요?
- [x] 빌드는 성공했나요?
- [x] 코드 포맷팅을 진행했나요?
- [x] PR 내부의 예시는 삭제하셨나요?

2024-08-06 14:01 UTC, lurgi reviewed
추상화 아주 멋지게 해주셨네용!! 몇가지 코멘트 남겨드렸습니다! 

1. 공고 카드가 버튼의 역할을 해야함으로, hover event가 들어가는 이상, 커서 pointer를 카드에 넣어야할 것 같습니다.
2. 제가 지금 생각하기론, 공유 버튼의 효용이 없다고 생각됩니다만. 저 버튼이 디자인 된 이유에 대해서 이야기를 해볼 필요가 있을 것 같습니다!
결론은 공유 버튼에 대해서 논의해보고, 뺄 것 같으면 hover 그림자와 cursor를 함께 사용하고, 필요한 기능이라면 큰 카드에 대한 그림자 transition을 삭제하고, 공고 바로가기 버튼과 같은 UI에 대해서 생각해볼 필요가 있을 것 같습니다.

감사합니다 아르~👍

2024-08-07 01:45 UTC, seongjinme commented on frontend/src/components/recruitment/RecruitmentCard/index.tsx
> +          {Array.from(postStatsMap).map(([label, value]) => (
`object` 타입으로 넘어오는 데이터는 순서 보장이 되지 않기 때문에 이렇게 작성했어요. 다만 코드를 다시 살펴보니 `object` -> `Map` -> `Array` 순으로 데이터를 변환하는 것은 불필요해 보이네요. `object` -> `Array`로 바로 변환되도록 코드를 수정했습니다. :)

* [refactor: stat 항목들을 Map에서 Array로 관리하도록 변경](https://github.com/woowacourse-teams/2024-cruru/pull/283/commits/04492364ba26aca5c26e36ab22385299c2174d44)

2024-08-07 02:00 UTC, llqqssttyy requested changes
아르 작업 고생하셨습니다! 역시나 꼼꼼한 작업물 좋네요.
제가 피그마 검수를 제대로 못한 관계로 스타일 부분에서 수정 요청이 있는데, 이 부분만 반영해 주시면 감사할 것 같습니다..!🥲

2024-08-07 02:05 UTC, seongjinme commented on frontend/src/components/recruitment/RecruitmentCard/index.tsx
> +          onClick={() => onClickShareButton(dashboardId)}
인자가 포함된 핸들러 함수의 경우 콜백으로 한 번 감싸주어야 해요. 이렇게 하지 않고 `onClickShareButton(dashboardId)`를 prop으로 바로 전달하면, 이 컴포넌트가 렌더링될 때 저 함수가 곧바로 실행될 거에요.

2024-08-07 02:09 UTC, seongjinme commented on frontend/src/components/recruitment/RecruitmentCard/style.ts
> +  color: ${({ theme }) => theme.baseColors.grayscale[900]};
위 내용에 해당되는 모든 스타일 요소에 대해 아래 커밋으로 변경 완료했습니다. :)

* [style: 텍스트 기본 색상(default/block) 코드 적용](https://github.com/woowacourse-teams/2024-cruru/pull/283/commits/cd61d3a32dac6fdc7cb74d4734f01d32b25712eb)

2024-08-07 04:44 UTC, seongjinme commented
피드백 주신 내용들을 모두 반영하였고, 앞서 함께 논의하였던 대로 '모집 상태'에 따른 Flag 표시를 추가하였습니다.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/27023eb6-8f1c-4c15-b624-fc2b63ce2e7f">

Flag는 아래의 3가지로 구분됩니다.
* `planned` : "모집 예정"
* `inProgress` : "모집 진행 중"
* `closed` : "모집 마감"

<img width="133" alt="image" src="https://github.com/user-attachments/assets/6c125780-8be5-4486-9d14-edfbd5cc7701">

관련하여 한 가지 이슈가 남아있어요. 현재 대시보드 목록 조회 API 스펙에 따르면, 마감 시각은 `endDate`로 들어오지만 시작 시각은 포함되어 있지 않습니다. 이 문제는 API 스펙이 업데이트 되면 해결 가능할 것 같습니다.

2024-08-07 04:50 UTC, lurgi approved these changes
고생하셨어용~

2024-08-07 05:29 UTC, llqqssttyy commented on frontend/src/components/recruitment/RecruitmentCard/index.tsx
> +          onClick={() => onClickShareButton(dashboardId)}
아하, TextEditor 컴포넌트 안에서도 같은 패턴이 보여서 여쭤봤어요. 인자 전달을 위해서 필요한 코드네요~

2024-08-07 05:31 UTC, llqqssttyy approved these changes

2024-08-07 08:48 UTC, seongjinme commented
두 가지 변경사항이 발생하여 다시 코드 리뷰를 요청 드립니다.

* 대시보드 API 스펙 변경에 따라 모집 시작일(`startDate`)을 추가 prop으로 받고, 공고 진행 상태를 표기하는 로직에도 이를 반영했어요.
* 타임존 설정, 날짜의 '시/분/초' 데이터 오차로 인해 발생 가능한 '모집 진행 상태' 로직의 버그를 수정했어요.

2024-08-07 09:01 UTC, lurgi approved these changes
변경사항 확인하였습니다! 감사합니다~

2024-08-07 09:06 UTC, llqqssttyy approved these changes
고생하셨습니다~!

2024-08-07 09:08 UTC, merged