refactor-be(Applicant): Facade Service 계층 도입
woowacourse-teams/2024-cruru pull request #318
Opened 2024-08-07 10:56 UTC by Dobby-Kim

- #315 

## 목적

Applicant 도메인에 Facade Service를 도입합니다.

## 작업 세부사항
- [x] Applicant 도메인 관련 Service 로직 분리
- [x] Test 수정 및 작성

## 참고 사항
bottom-up 방식으로 ERD상 하위 엔티티 도메인부터 작업을 진행해나갈 예정입니다.
완료된 PR의 경우 cherry-pick 또는 merge를 통해 본인의 코드에 적용해주세요

FACADE_ADOPTION_01-3

2024-08-07 13:39 UTC, cutehumanS2 requested changes
수고 많으셨습니다. 😸
간단한 코멘트 남겼으니 확인 부탁드립니다.

2024-08-07 13:39 UTC, cutehumanS2 commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +    void updateApplicantInformation() {
메서드명에 예외를 던지는 것을 검증한다는 의미가 들어가야 하지 않을까요?

2024-08-07 13:39 UTC, cutehumanS2 commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +        )).isInstanceOf(ApplicantNoChangeException.class);
```suggestion
        assertThatThrownBy(() -> applicantService.updateApplicantInformation(noChangeRequest, savedApplicant))
                .isInstanceOf(ApplicantNoChangeException.class);
```
개행이 이렇게 들어가야 하지 않을까요?

2024-08-07 13:39 UTC, cutehumanS2 commented on backend/src/test/java/com/cruru/applicant/service/facade/ApplicantFacadeTest.java
> +        );
별 거 아니지만 actual과 expected 위치가 반대가 된 것 같아요.
>actual = basicResponse, processResponse, applicantResponse
>expected = process 

아닌가요? ? 저도 헷갈립니다. .

2024-08-08 00:59 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/applicant/service/facade/ApplicantFacadeTest.java
> +        );
아 냥인 말이 맞는 것 같습니다ㅋㅋㅋ
바로 적용할게요

2024-08-08 02:13 UTC, HyungHoKim00 requested changes
고생하셨습니다. 리뷰 확인 부탁드려요

2024-08-08 02:13 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/answer/service/AnswerService.java
> +public class AnswerService {
테스트가 없네용..

2024-08-08 02:13 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/applicant/service/ApplicantService.java
> +    public void updateApplicantInformation(ApplicantUpdateRequest request, Applicant applicant) {
성공 테스트가 없네요~

2024-08-08 02:24 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/applicant/service/facade/ApplicantFacade.java
> +        List<QnaResponse> qnaResponses = answerService.toQnaResponses(answers);
두가지 이유에서 다음과 같이 진행했습니다.
1.
Service -> Facade => Domain 엔티티 전달
Service -> Facade => Entity to DTO 변환
Facade -> Controller => DTO 전달

2. Facade에서 다른 도메인에 속하는 DTO 변환 로직을 계속 생성하게 된다면, 다른 Facade에서 해당 도메인을 다룰 때에도 코드 중복이 발생할 수 밖에 없습니다.

따라서 도메인이 자신의 도메인 패키지에 존재하는 DTO 변환 책임을 가지도록 하기 위해 위와 같이 코드를 작성했습니다.

위에 원래 작성되어있던 매서드를 확인해보니 Process DTO가 Applicant Facade에서 변환되고 있네요! 이 점도 Process Service에서 직접 처리하도록 하겠습니다

2024-08-08 03:22 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/applicant/service/facade/ApplicantFacade.java
> +        applicantService.updateApplicantInformation(request, applicant);
명오를 따르겠습니다..

2024-08-08 03:22 UTC, cutehumanS2 approved these changes

2024-08-08 04:53 UTC, HyungHoKim00 requested changes
고생하셨습니다. 자잘한 변경사항과 질문이 존재하여, 다시 RC 드립니다.

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +    void updateInformationApplicantProcess() {
테스트하는 메서드명은 updateProcess인데 테스트 메서드명은 다른 이유가 있나요?

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/answer/service/AnswerServiceTest.java
> +    @Test
테스트에 @DisplayName이 누락되었네요.

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/applicant/service/ApplicantService.java
> +        return applicant.getName().equals(request.name()) && applicant.getEmail().equals(request.email())
&& 전에 개행을 추가하는 게 더 읽기 쉬울 것 같아요.

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/answer/service/AnswerService.java
> +    private AnswerResponse toQnaResponse(Answer answer) {
AnswerResponse로 응답 클래스명을 변경했다면 메서드명도 변경되어야하지 않을까요?

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/applicant/service/facade/ApplicantFacade.java
> +        List<AnswerResponse> answerResponses = answerService.toAnswerResponses(answers);
[질문] 위 두줄은 answerService의 두 메서드가 따로 불러와지는 이유가 있을까요?

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/answer/service/AnswerServiceTest.java
> +        List<Answer> expectedAnswers = answerRepository.saveAll(List.of(expectedAnswer1, expectedAnswer2));
이 메서드에서 repository를 호출하여 db에 저장하는 로직이 존재할 필요가 있나요?

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +        }).isInstanceOf(ApplicantNoChangeException.class);
```suggestion
        assertThatThrownBy(() -> applicantService.updateApplicantInformation(applicantId, noChangeRequest))
                .isInstanceOf(ApplicantNoChangeException.class);
```
이 변경사항은 어떤가요?

2024-08-08 04:53 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/process/service/ProcessService.java
> +    public ProcessSimpleResponse toProcessSimpleResponse(Process process) {
[질문]
이 메서드에 대한 테스트가 존재하지 않는 이유는 단슌 response 변환 메서드이기 때문인가요?
그렇다면, toAnswerResponses() 메서드에 테스트가 존재하는 이유는 뭔가요?
도비가 생각했을 때 response로 변환하는 로직은 검증되어야 하나요?

2024-08-08 04:54 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/applicant/controller/ApplicantControllerTest.java
> +    void updateInformationApplicantProcess() {
아 리팩터링을 했는데 같이 안바뀌었네요
바로 적용하겠습니다.

2024-08-08 04:57 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/applicant/service/facade/ApplicantFacade.java
> +        List<AnswerResponse> answerResponses = answerService.toAnswerResponses(answers);
앞선 Comment에서 설명드린 바와 같습니다. Service가 Facade로 도메인 entity를 전달하는 것이 기본이기 때문입니다.

그리고 Service에게 해당 도메인 패키지의 DTO 변환 책임이 있습니다.

2024-08-08 04:58 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/applicant/service/ApplicantService.java
> +        return applicant.getName().equals(request.name()) && applicant.getEmail().equals(request.email())
그치만,, 코드 리포맷팅을 적용하면 다시 줄이 바뀌는걸요..

2024-08-08 04:59 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/process/service/ProcessService.java
> +    public ProcessSimpleResponse toProcessSimpleResponse(Process process) {
우선 Process Service 관련 로직은 다음 PR에서 다뤄질 예정이라 필요한 메서드를 수정만 진행한 상태라 test가 없는 것입니동

2024-08-08 05:12 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +        }).isInstanceOf(ApplicantNoChangeException.class);
아 맞습니다 의미없는 코드 블록을 생성했군요!
제거했습니다 :)

2024-08-08 05:14 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/answer/service/AnswerServiceTest.java
> +        List<Answer> expectedAnswers = answerRepository.saveAll(List.of(expectedAnswer1, expectedAnswer2));
맞말추입니다

2024-08-08 05:57 UTC, HyungHoKim00 requested changes
수정 사항과 질문이 조금 있어 RC 드립니다.

2024-08-08 05:57 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/process/service/ProcessService.java
> +    public ProcessSimpleResponse toProcessSimpleResponse(Process process) {
메서드 생성 시점에서 테스트를 만드시는 것이 좋을 것 같습니다. 만약 다른 사람이 ProcessService 관련 로직을 수정한다고 했을 때, 이미 이 로직에는 테스트가 있다고 기대하지 않을까요?

2024-08-08 05:57 UTC, HyungHoKim00 commented on backend/src/main/java/com/cruru/applicant/service/ApplicantService.java
> +        return applicant.getName().equals(request.name()) && applicant.getEmail().equals(request.email())
저는 리포맷을 해도 줄이 올라가지지 않는데, 설정을 확인해 볼 필요가 있을 것 같아요. 가독성을 위한 개행을 하는데 리포맷팅 과정에서 줄이 다시 올라가는건 문제가 있는 것 같아요.

2024-08-08 05:57 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +                () -> applicantService.updateApplicantInformation(applicantId, noChangeRequest)
[질문] `assertThatThrownBy(` 이후에 개행이 있는 이유가 있나요?

2024-08-08 05:57 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/answer/service/AnswerServiceTest.java
> +        Question question2 = questionRepository.save(QuestionFixture.createShortAnswerQuestion(null));
저번 코멘트에서 제가 전체 범위를 명시하지 않아 놓치신 부분 같네요. 위의 applicant와 question도 저장될 필요가 없지 않나요?

2024-08-08 05:57 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/util/fixture/AnswerFixture.java
> +    public static Answer shortAnswer(Question question, Applicant applicant) {
위의 firstAnswer, secondAnswer가 존재하는데 shortAnswer라고 따로 픽스처를 생성하신 이유가 있나요? 만약 shortAnswer임을 명시하고 싶다면 firstAnswer, secondAnswer를 firstShortAnswer 등으로 변경하는 건 어떤가요?

2024-08-08 06:06 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/process/service/ProcessService.java
> +    public ProcessSimpleResponse toProcessSimpleResponse(Process process) {
맞습니다
하지만 현재는 리뷰 편의성을 위해 방대한 File Change를 방지하고자 PR을 나눈것이고, 통합 PR 기준으로 보면 아직 작업 중에 있다고 생각해주시면 됩니다.
바로 다음 Issue 작업에서 진행하겠습니다

2024-08-08 06:06 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
> +                () -> applicantService.updateApplicantInformation(applicantId, noChangeRequest)
이유는 Looks Good To Me였습니다

2024-08-08 06:16 UTC, Dobby-Kim commented on backend/src/test/java/com/cruru/util/fixture/AnswerFixture.java
> +    public static Answer shortAnswer(Question question, Applicant applicant) {
Question에도 순서가 있으므로 그 Question에 대한 Answer에 순서를 표현한 답변으로 Fixture을 만들었고,
Question 유형에 따라서 답변이 필요하여 shortAnswer을 만들었습니다.

순서와 유형을 조합하여 Fixture을 만든다면 너무 많은 조합 경우의 수가 발생할 것 같아 우선은 필요한 유형만 생성했습니다

2024-08-08 06:17 UTC, Dobby-Kim commented on backend/src/main/java/com/cruru/applicant/service/ApplicantService.java
> +        return applicant.getName().equals(request.name()) && applicant.getEmail().equals(request.email())
한 번만 치면 유지되긴 하는데 명오도 아마 두 번 연속 리포맷하면 다시 올라갈겁니다..ㅎ

일단 바꿔놓을게요

2024-08-08 06:28 UTC, HyungHoKim00 approved these changes
고생하셨습니다~

2024-08-08 06:30 UTC, merged