docs-be: RESTDocs 문서화 적용
woowacourse-teams/2024-cruru pull request #645
Opened 2024-09-08 17:01 UTC by Chocochip101

## 작업 내용
- RESTDocs를 통해 API 문서 생성했습니다.

## 참고 사항
- 스프링 실행 후 localhost:8080/docs/index.html 로 들어가시면 문서를 확인할 수 있습니다.
- MVC config에서 로그인 인터셉터에서 `/docs/index.html` path를 제거했습니다.
- 평가 점수 API에서 `@Valid`가 없어서 추가했습니다. [Link](https://github.com/woowacourse-teams/2024-cruru/commit/a740e8d5e9f6cf12f7f07453242d6ebfb2a4bbfb)
- docs에 토큰이 필요한 API에 명시했습니다.
  - 제가 존경하는 분의 [문서화 영상](https://youtu.be/YHhVSuFQUyQ?si=BEGsJGo8ykCA7m1l)과 [PR](https://github.com/woowacourse/spring-roomescape-payment/pull/81/files#diff-754128cfa94af0cb5f975367291e7ef5b9656f3f07acfd4e73b6c1cfca5a5513)을 참고했습니다.
- 리뷰해야할 코드의 양이 많습니다. 🙇

## 관련 이슈
- closes #642 
- closes #177 

## PR 체크리스트
- [x] 테스트는 모두 통과했나요?
- [x] 빌드는 성공했나요?
- [x] 코드 포맷팅을 진행했나요?
- [x] PR 내부의 예시는 삭제하셨나요?

2024-09-09 04:22 UTC, HyungHoKim00 requested changes
진짜 고생 많으셨습니다 초코칩. 엄청난 작업량이네요.
코멘트 확인해주세요~

추가적으로, 존재하지 않는 ~~~ 등 중복되는 오류가 발생하기도 하는데요, 이 경우를 모든 테스트에서 확인하기도 힘들고 누락될 가능성도 높아 보여요. 한 링크로 처리해볼 수 있는지 확인해보는 것도 좋을 것 같아요.

2024-09-09 04:22 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/member/controller/MemberControllerTest.java
> +                        responseFields(
필드를 명시해놓은 이유가 있나요?

2024-09-09 04:22 UTC, HyungHoKim00 commented on backend/src/docs/asciidoc/process.adoc
> +=== 프로세스 수정
'실패: 존재하지 않는 대시보드'도 추가해주세요~

2024-09-09 04:22 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +                        requestCookies(cookieWithName("token").description("사용자 토큰")),
현재 테스트가 token을 사용하고 있지 않은 것 같은데 추가한 이유가 있나요?

2024-09-09 04:22 UTC, HyungHoKim00 commented on backend/src/docs/asciidoc/question.adoc
> +==== 성공
'실패: 존재하지 않는 질문'도 추가해주세요!

2024-09-09 04:22 UTC, HyungHoKim00 commented on backend/src/docs/asciidoc/process.adoc
> +operation::process/create-fail/dashboard-not-found[snippets="http-request,request-cookies,query-parameters,http-response"]
실패하는 테스트에 대해선 request-field를 받지 않는 것을 의도하신건가요? 그렇다면 다른 스니펫도 확인해봐야 할 것 같아요~(ex: applicant 지원자들의 프로세스 일괄 수정)

2024-09-09 08:42 UTC, xogns1514 requested changes
수고하셨습니다 초코칩! 작업량이 엄청 많았을텐데 고생하셨어요. 
오타 및 기존 api 문서와 일치여부 위주로 보았습니다.

2024-09-09 08:42 UTC, xogns1514 commented on backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java
> +    @DisplayName("프로세스가 존재하지 않을 경우, 404를 응답한다.")
테스트명과 Display 명이 일치하지 않습니다!

2024-09-09 08:42 UTC, xogns1514 commented on backend/src/test/java/com/cruru/question/controller/QuestionControllerTest.java
> +            fieldWithPath("orderIndex").description("선택지의 필수 여부")
```suggestion
            fieldWithPath("orderIndex").description("선택지의 순서")
```
field 명과 설명이 불일치 합니다.

2024-09-09 08:42 UTC, xogns1514 commented on backend/src/test/java/com/cruru/dashboard/controller/DashboardControllerTest.java
> +            fieldWithPath("dashboardId").description("동아리의 id"),
```suggestion
            fieldWithPath("dashboardId").description("대시보드의 id"),
```

2024-09-09 08:46 UTC, xogns1514 commented on backend/src/test/java/com/cruru/question/controller/QuestionControllerTest.java
> +                        requestFields(fieldWithPath("questions").description("변경할 질문들"))
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/07fedcf3-878d-4bb3-b3dc-6ba18e7814fe">

제가 로컬에서 확인할때, request field가 보이지 않더라고요. 이부분 확인해주시면 감사하겠습니다.

2024-09-09 11:23 UTC, xogns1514 requested changes

2024-09-09 11:23 UTC, xogns1514 commented on backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
> +            fieldWithPath("isRejected").description("지원자의 합불여부"),
```suggestion
fieldWithPath("isRejected").description("지원자의 불합격 여부"),
```

2024-09-09 13:23 UTC, HyungHoKim00 requested changes
고생하셨습니다 초코칩. 막판에 잘못된 리뷰도 몇개 남겨놨는데 잘 걸러내셨네요. github actions도 야무집니다.
사소한 변경 제안사항이 남아있어 RC 한번만 더 드립니다. 확인해주세요.

2024-09-09 13:23 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/applyform/controller/ApplyFormControllerTest.java
> +    private static final FieldDescriptor[] QUESTION_REQUEST_FIELD_DESCRIPTORS = {
변수명이 조금 어색하네용. APPLICANT_SUBMIT 혹은 APPLICANT_REPLY 정도는 어떠신가요?

2024-09-09 13:23 UTC, HyungHoKim00 commented on backend/src/test/java/com/cruru/auth/controller/AuthControllerTest.java
>                  .cookie("token", token)
로그아웃에도 Set-Cookie 설정이 있는 것으로 아는데 문서에 추가해주시면 좋을 것 같아요~

2024-09-10 00:04 UTC, Chocochip101 reviewed
리뷰 반영과 로그아웃 관련 예외처리 케이스도 추가했어요!

확인 부탁드립니다 🙇

2024-09-10 00:33 UTC, HyungHoKim00 approved these changes
고생하셨습니다 초코칩. 반영해도 되고 안해도 되는 수정사항만 하나 남겼습니다 ㅎㅎ.

2024-09-10 00:33 UTC, HyungHoKim00 commented on backend/src/docs/asciidoc/dashboard.adoc
> +operation::dashboard/read[snippets="http-request,request-cookies,query-parameters,response-fields,http-response"]
이번 수정사항을 보니 http-response -> response-fields 순서를 의도하신 것 같은데 맞다면 여기도 수정하는건 어떨까요?

2024-09-10 00:52 UTC, xogns1514 approved these changes
수고하셨습니다!!

2024-09-10 01:07 UTC, merged